### ISSUE TITLE
Enhancement Request - Allow multiple contributions to be loaded

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/geoform-template-js#201]
As a control point contributor, I need to submit multiple control points at once without having to fill out the form for multiple times for each point.

Currently you can attach a document that includes multiple positions, but you still have to process it with another workflow (i.e. import excel to points).

**Comment by daFiter** [comment]
We are going to use geoform to collect camera locations for the police (public input). We were wondering if someone has more then one camera if they can add all the locations without filling out the form multiple times. I think muitipoint would work or the ability to add the fields to all points created on the map. I see that this has been closed. Did the enhancement ever get added or was this dropped?
