### ISSUE TITLE
Add browsing mode for GeoForm Submissions

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#273]
We need a mode for browsing submissions with the GeoForm. Originally, we were thinking that we would use a different template but nothing good exists in order to page through results.

We need a separate page/app in the GoeForm app, lets call it viewer.html. This will have a title, short description, legend, a share button, button to submit (which will take you to the index page to submit an entry) and a bottom or side panel that will allow users to see GeoForm submissions.

If the feature layer, supports pagination (result offset and result record count) then it will have buttons to page through the results and easily browse GeoForms. Otherwise, they can just click around to browse. It will not use a popup. Maybe we allow them to filter results by certain attributes? maybe that's scope creep though.

@sTriche @DerrickBurke @pjdohertygis @julio8a We will need a comp/design for this. It could be a full-screen map or it may not be. Ushahidi allows you to toggle between a map/list view and maybe that would be helpful for users.

The mode should be responsive.

Somewhere on the GeoForm  in submit mode (maybe under the map), there will be a link to view existing submissions. Once they submit, the dialog will show a link there as well.

Then, once we have this mode, we can add editing capability onto it if they login as an admin? This is issue #156

**Comment by CTDisasterManagement** [comment]
@driskull,

Just wanted to let you know the known issues in delivered code.
Known Issues:
1.	Sometimes feature is not highlighted
2.	UI get distorted in some themes
3.	UI issues in small screen devices
4.	Wrong geometry gets highlighted if list item is clicked rapidly 
5.	Resize issues in map
6.	UI for “Load More” button needs to be worked upon

Work in progress on following tasks:
1.	Pagination support for 10.3 layers
2.	Adding new tab in navigation panel if author selects “All Layer ” in author mode 

Queries:
1.	We have added “Go To Viewer Mode” button on submit mode (end user mode) and we are thinking of adding the same in share dialog(User can go to viewer mode after submitting the entry). Will this work?

Thanks!

**Comment by driskull** [comment]
Thanks for the notification @CTDisasterManagement .

Lets have the button say "View submissions". We can put it in the share modal and to the right of the submit button with a default (secondary) button class so that it's not as important.

Those links above don't take me to the browse mode.

**Comment by CTDisasterManagement** [comment]
@driskull 

We will implement the suggested changes.
The link for end user mode will open the form and you will find "Go To Viewer Mode" button next to "Submit Entry" button.

Thanks!

**Comment by driskull** [comment]
"View submissions" instead of "Go To Viewer Mode" please. Thanks

**Comment by CTDisasterManagement** [comment]
@driskull,

We have added "View submissions" button in share modal.Please have look at it and let us know your feedback.
![viewsubmissions_button](https://cloud.githubusercontent.com/assets/5261405/6668473/342225fe-cc19-11e4-80c9-3a0f1cece95e.PNG)

Thanks!!

**Comment by driskull** [comment]
@CTDisasterManagement I think that works. thanks

**Comment by CTDisasterManagement** [comment]
Thanks @driskull
