### ISSUE TITLE
Add support for all layers in webmap

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#287]
We got a request to support adding submissions for all layers. So an author could configure  a geoform to use all layers and then in user mode a user would first pick a layer from the webmap in a dropdown and then would get all the fields for that layer to enter.

@pjdohertygis do we want to support this?

**Comment by CTDisasterManagement** [comment]
@driskull 

Here is demo link for 'all layer' functionality:
Author Mode:
http://203.199.47.152/LimNextGen/geoform_alllayer/
appid=bbcd4e8082704f09b44def308bc89c54&edit=t

User Mode:
http://203.199.47.152/LimNextGen/geoform_alllayer/
appid=bbcd4e8082704f09b44def308bc89c54

Username:sagarnair_cssl
Password: CSSL#2016

Please let us know your feedback.

Thanks

**Comment by driskull** [comment]
@CTDisasterManagement Seems to work well. We would like the layer dropdown to appear as just another item within the form at the top. Instead of being separated from the rest of the form fields.

In the author view:
The default layer selection should be "All" instead of "Select Layer". If there are no feature layers then we should disable the menu. The rest looks good. Thanks

**Comment by CTDisasterManagement** [comment]
@driskull 

We were thinking of keeping the layer drop down separate, because on layer change the whole form will be created again and if layer drop down is part of form div, then it will be hidden and shown on every layer change.

Thanks!

**Comment by driskull** [comment]
Lets discuss at next meeting. It doesn't look right as it currently is. @pjdohertygis may have some feedback.

**Comment by CTDisasterManagement** [comment]
Sure.

Thanks!

**Comment by CTDisasterManagement** [comment]
@driskull 

We have done some changes in 'All Layer' functionality.Please have a look it.
Author Mode:
http://203.199.47.152/LimNextGen/geoform_alllayer/?appid=bbcd4e8082704f09b44def308bc89c54&edit=t

User Mode:
http://203.199.47.152/LimNextGen/geoform_alllayer/?appid=bbcd4e8082704f09b44def308bc89c54

Username:sagarnair_cssl
Password: CSSL#2016

Thanks!

**Comment by driskull** [comment]
That looks great. Lets just change the text in the user mode from "Select Layer" to "Choose Form".

**Comment by CTDisasterManagement** [comment]
Sure Matt.
We will do the same and send a new pull request tomorrow.

Thanks!

**Comment by CTDisasterManagement** [comment]
@driskull 

We have sent pull request.Please have a look at it.
Previously we were having fields array(this.config.fields=[]), but now we are using object for the same as we can have n number of layers to be stored.Just wanted to let you know this as this is measure change.

If this issue is merged in development branch then we can easily start working on "All Layer" support for browse mode as it is related to this issue.

Thanks!

**Comment by driskull** [comment]
Hey @CTDisasterManagement Is it a breaking change? Sounds like it. We need to support all existing applications that are currently out there not configured with multiple layers. So we'll need to check to see if the fields is an array or an object and handle it as we need to so it doesn't break. Does that make sense?

**Comment by CTDisasterManagement** [comment]
Yes @driskull it does make sense.

When application loads, if this.config.fields is an array then we can convert it to an object 
EG: this.config.fields['layerId']=fieldsArray;
So the code will work with minimal changes.
Can we go ahead and implement the same?

Thanks!

**Comment by driskull** [comment]
Yes, that will work. thanks! :+1:

**Comment by CTDisasterManagement** [comment]
@driskull 

We have sent a pull request which supports configured fields in array and object format.
So it should work with old appid, we are testing it with different scenarios.

Thanks!

**Comment by driskull** [comment]
awesome. thanks!
