### ISSUE TITLE
Default Date/Time 12/29/1899 4:00 PM

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#299]
![image](https://cloud.githubusercontent.com/assets/4256979/4532090/efebf5ac-4d8f-11e4-9e62-95d0eb438a35.png)

Here is the feature service - date is set as a required field - not sure why the Default Date is set to 12/29/1899 4:00 PM when I use preview mode. 

http://disasterresponse.maps.arcgis.com/home/item.html?id=03e7ac020c964d5fb5af8a43b0ff01f4

Expected behavior would default to today's date?

**Comment by pjdohertygis** [comment]
Matt - 

This popped up again...

![image](https://cloud.githubusercontent.com/assets/4256979/12409799/7aea06f4-be3b-11e5-8727-eaa700fd72d7.png)

I will see if I can fix the feature service, but why wouldn't the date / time picker just default to today's date instead of 1899. When would 1899 ever be expected behavior? 

I know it may not be a bug - but perhaps this could be 'enhanced'?

**Comment by bogibrynjar** [comment]
We have encountered this also in the latest version of the Geoform as well when a date field is set to required (NULL not allowed in the Geodatabase). When making an on premise feature service where the date field is required the default value is 00:00:00 in the feature's default edit template (in ArcMap).

I think I got around this last time (at least with on premise feature services) by managing the feature's edit template in the AGOL web map after publishing the service and putting it in the web map. There you should be able to set the default value of the date field on new features to "empty" and then it starts empty in the Geoform.

I've forgotten to do that a couple of times and users constantly complain about it :)

**Comment by pjdohertygis** [comment]
Here is a potential workaround using ArcGIS Pro. Design the Field - change the default to January 1 of the current year. This returns expected behavior on the GeoForm. I am not sure how you would do this without ArcGIS Pro other than creating a new field via the attribute table in the web map. 

Please consider and enhancement for this feature. 

![image](https://cloud.githubusercontent.com/assets/4256979/12423501/ccc9e814-be99-11e5-89b4-6a3ac8ad29e0.png)

![image](https://cloud.githubusercontent.com/assets/4256979/12423528/f0134e0a-be99-11e5-9487-a8dc83629152.png)

**Comment by jgravois** [comment]
@driskull if you drop the last three zeros from `-2209161600000` > the UTC equivalent is `Sat, 30 Dec 1899 00:00:00 GMT`.  

@nixta where else were you seeing this behavior the other day?

**Comment by nixta** [comment]
@jgravois I was trying to get the max date out of a Feature Service table based off a date field, for which I had to use statistics. Once I'd figured out the JSON parameters, it was returning the max date including milliseconds (and also setting the output statistic field to a numeric type, as it happens).

**Comment by driskull** [comment]
There should be an option in the GeoForm to set the current date. There's a gear options icon you can see more checkboxes when configuring a date field. That should do it.

Otherwise, I could look into automatically handling it when the date is matched to "00:00:00" or whatever it is that is causing the issue.

-Matt

**Comment by pjdohertygis** [comment]
It is worth testing on your end - but it did not appear that the current date setting was able to override the 1899 issue.

**Comment by driskull** [comment]
Should be fixed in next update. You could download and test or test via the github URL.

http://esri.github.io/geoform-template-js/

http://esri.github.io/geoform-template-js/?appid=[my apps id]

**Comment by pjdohertygis** [comment]
Excellent!
