### ISSUE TITLE
issue/performance: Map fails to load on 3G connection on mobile devices

### ISSUE THREAD

**Issue by bogibrynjar** [Esri/geoform-template-js#349]
Hi,

We have been receiving complaints from users that the form fails to load on mobile phones that are on a 3G data connection. The error has been screenshot and can be seen here below. 

![screenshot_2014-12-01-13-42-01](https://cloud.githubusercontent.com/assets/8677318/5246357/f37f9c2c-795f-11e4-883c-087950cc5696.png)

The issue seems to be one of a timeout limit on the map. Unfortunately we are using an ESRI basemap and a hosted feature service so these are factors we can not change. Just wanted to let you know about this since it's probably nothing wrong in the Geoform code but definitely something to think about to make the whole form code as "slim" as possible to really help with the use of it in the field through mobile devices.

**Comment by driskull** [comment]
closing. we'll use #379.
