### ISSUE TITLE
Drop down boxes should have the option of searchable text

### ISSUE THREAD

**Issue by sirws** [Esri/geoform-template-js#350]
It would be great to have a dropdown for domain fields that allows for more robust searching.  Something like this control would be great: http://ivaynberg.github.io/select2/

**Comment by CTDisasterManagement** [comment]
@driskull,

Here is the link:
http://203.199.47.152/LimNextGen/filterSelect/?appid=f3e93738999a4a5f92aa0535721113cb

Please let us know if this will work.

Thanks!

**Comment by driskull** [comment]
Yes, those look good. We don't want every drop down to be using this filter plugin though. Only ones that are set in the builder.

Thanks

**Comment by CTDisasterManagement** [comment]
Sure.
We will send a pull request soon.

Thanks

**Comment by CTDisasterManagement** [comment]
@driskull

**Comment by driskull** [comment]
looks good!

**Comment by vxsunstriderxv** [comment]
The 'Filter Select' works great however I have noticed the filter select option is not available for domains that are linked to subtypes.  Should this option be available for such domains?

In  the image below, the GENUS_NAME field is a subtype and the HOST_GENUS_SPECIES field is a domain linked to the subtype.  As you can see, while all other subtypes or domians have been set to filter select, the option is not available for the HOST_GENUS_SPECIES field.

Thanks

![geoform 1jpg](https://cloud.githubusercontent.com/assets/9136708/6614282/4e0fb94a-c890-11e4-8ebf-37c08d289ff2.jpg)

**Comment by driskull** [comment]
Makes sense.

**Comment by CTDisasterManagement** [comment]
Hi @driskull 

We can see that the options available here for HOST_GENUS_SPECIES field are 'text' and 'checkbox' so this field should be a integer type field as per the code.

Can you please provide us with the layer so that we can further investigate into this as the screen shot above gives us an impression that field is not domain type but an integer type.

Thanks!

**Comment by vxsunstriderxv** [comment]
Hi @CTDisasterManagement 

Here is the layer:

http://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/APHAMobileDataV4/FeatureServer/0

Thanks

**Comment by CTDisasterManagement** [comment]
Hi @driskull,
The 'Host_genus_Species' field is integer field as we can see here:

![image](https://cloud.githubusercontent.com/assets/5261405/6747134/b636356a-cefa-11e4-817a-cb22c184294d.png)

The options populating in the 'Display As' column of 'Host_genus_Species' field are correct as textbox  and checkbox are the desired options of integer field.

Thanks!

**Comment by vxsunstriderxv** [comment]
Hi @CTDisasterManagement 

Thanks for looking into this.  I'm slightly confused though as other interger fields seem to be displaying the filter select option.  The INSPECTION_TYPE field for example is an interger but the screen shot shows it is set as filter select:

INSPECTION_TYPE (type: esriFieldTypeInteger, alias: Inspection Type, SQL Type: sqlTypeOther, nullable: false, editable: true)

The only difference between this domain and the HOST_GENUS_SPECIES domain is that it is not linked to a subtype field.

Thanks

**Comment by driskull** [comment]
@CTDisasterManagement can you look into this?

**Comment by CTDisasterManagement** [comment]
@driskull @vxsunstriderxv,

Sure, we will check this and get back to you

Thanks!

**Comment by CTDisasterManagement** [comment]
@driskull @vxsunstriderxv,

As we can see here, the Inspection_Type field has domain values whereas Host_Genus_Species doesn't have domain value.

![image](https://cloud.githubusercontent.com/assets/5261405/6797210/1d359bca-d225-11e4-9fba-4e815f0130b6.png)

![image](https://cloud.githubusercontent.com/assets/5261405/6797249/9c496a86-d225-11e4-9546-005a4e7cecf8.png)

Thanks!

**Comment by driskull** [comment]
@CTDisasterManagement yes, lets override it.
