### ISSUE TITLE
Provide ability to set the location based on URL parameters.

### ISSUE THREAD

**Issue by sirws** [Esri/geoform-template-js#351]
I want to capture a bunch of data at a specific location and I don't want to the user to have to select the location every time.  It would be nice to just have a parameter (or parameters for each location type) that start the form with the location set based on those parameters:

http://esri.github.io/geoform-template-js/?lat=47&long=-117
or
http://esri.github.io/geoform-template-js/?usng=11TMN9625527190

**Comment by CTDisasterManagement** [comment]
@driskull,

Fix for this issue is already checked in, can you please verify and let us know if anything else is required?

Thanks

**Comment by driskull** [comment]
Can we rename mylocation to locate? Other than that it looks and works good.

**Comment by jakc** [comment]
An addition to this enhancement would be to support searching against layer level searches setup in the Web-Map.  

![Image of Issue](https://dl.dropboxusercontent.com/u/11426532/1.png)
