### ISSUE TITLE
GeoForm. The date is displayed mm/dd/yyyy instead of dd/mm/yyyy

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#355]
Steps: 1. Create a Web Map, save and share. 2. Use GeoForm template and Publish 3. The Date format is displayed mm/dd/yyyy instead of dd/mm/yyyy Team: ArcGIS Online Functional Area: ArcGIS.com Description: ArcGIS Online Application Templates &gt; Web Applications Priority: Medium
Salesforce ID: BUG-000083804
Salesforce Submitter: ronit rom
Salesforce Submit Date: 12/04/2014 11:05 AM
Salesforce Bug Type: Failure/Error
Salesforce Severity: Medium
Salesforce Attachments: GLOBAL-006829.png
Salesforce Attachments Location: \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000083804
Repro Data: \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000083804
Work Around: (n/a)
Product: ArcGIS Online
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: 3.6
Planned Version Fixed: (n/a)
Comment: (n/a)

![geoformapp_datenotheformat](https://cloud.githubusercontent.com/assets/1231455/5308428/79d01f32-7bcb-11e4-8217-94462ce89c32.png)

**Comment by pjdohertygis** [comment]
Since many countries outside the US use the mm/dd format - should that be a configurable option? How does this work elsewhere in ArcGIS Online?

**Comment by driskull** [comment]
We should put the format in the NLS file so that it can be correctly put by the translators. @CTDisasterManagement see this line: https://github.com/Esri/map-gallery-template-js/blob/master/nls/template.js#L7

**Comment by driskull** [comment]
hi @CTDisasterManagement did this make it into the NLS? If not, we need to put this in ASAP.

Thanks

**Comment by CTDisasterManagement** [comment]
@driskull 

We tried reading date format from NLS. But if the date field is having range, some how all the dates are getting disabled.
We are using dojo locale format to set min and max date but if NLS has a format which is not present in dojo locale date format then code fails.

We will try to fix this ASAP and update you tomorrow.

Thanks!

**Comment by driskull** [comment]
ok thanks.

**Comment by CTDisasterManagement** [comment]
@driskull 

We have tested the date functionality with following date formats:
MM/DD/YYYY
DD/MM/YYYY
MMMM DD, YYYY
DD MMM YYYY
dddd, MMMM DD, YYYY
MM/DD/YYYY h:mm:ss a
DD/MM/YYYY h:mm:ss a
DD/MM/YYYY h:mm a
MM/DD/YYYY h:mm a
MM/DD/YYYY HH:mm	
MM/DD/YYYY HH:mm
MMMM YYYY
MMM YYYY
YYYY

We are testing it with all possible conditions.Please let us know in case of any changes.

Thanks!!

**Comment by driskull** [comment]
Thanks!
