### ISSUE TITLE
order and organize attribute in page tabs (decision tree)

### ISSUE THREAD

**Issue by ebonan** [Esri/geoform-template-js#365]
is it possible to arrange the attribite order and organize them in a page with tabs/ folders ?
In case of forms with many fields this could be very useful.
thank you 
Enrico

**Comment by driskull** [comment]
Hi @ebonan. Not currently, we'll investigate how to best do this. I'm thinking related tables in a database.

**Comment by ebonan** [comment]
Thank you. My question regarded only the possibility to visualize the internal  attributes of the feature service in a tab layout instead that the original "flat" form.
We have feature service with many many fields and it would be nice organize them in in the form like sections/ tabs.
Thank you for you great work,
Enrico

Inviato da iPad

**Comment by driskull** [comment]
Another part of this should be a decision tree structure.

**Comment by LisaNutt** [comment]
Hi, I notice that related tables is now available in Collector.  Is it available for GeoForm also?

**Comment by driskull** [comment]
@LisaNutt not yet :(
