### ISSUE TITLE
Ability to configure BasemapToggle basemaps

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#368]
@CTDisasterManagement The user should be able to set the basemap and defaultBasemap of the Basemap toggle widget.

**Comment by CTDisasterManagement** [comment]
@driskull,

Do you want us to add Two drop downs to configure the basemap and defaultBasemap?
This drop downs will go in "Options" tab.

Thanks!

**Comment by driskull** [comment]
Yes, that sounds good.

**Comment by driskull** [comment]
@CTDisasterManagement looks really good. Can we put the basemap image to the right of the input menu instead of on the left?

**Comment by CTDisasterManagement** [comment]
Sure @driskull .

Thanks!
