### ISSUE TITLE
Some fields not showing up in the GeoForm Viewer mode

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#369]
When I use this feature service to configure the GeoForm....

http://univredlands.maps.arcgis.com/home/item.html?id=c5f3e13951dd4dd9942e8dafc8e181c7

It shows up in the Builder here (you'll notice I did rearrange the fields a bit): 

![image](https://cloud.githubusercontent.com/assets/4256979/5607128/fda03470-9401-11e4-9b60-0a085e025fb5.png)

But not in the Preview or Viewer mode

![image](https://cloud.githubusercontent.com/assets/4256979/5607132/2567772a-9402-11e4-9c1a-fcfab9b72240.png)

Any ideas?

**Comment by pjdohertygis** [comment]
I am getting a similar bug with this 2nd version http://univredlands.maps.arcgis.com/home/item.html?id=b82bc53bede141a5b6f339bce644f7aa

**Comment by pjdohertygis** [comment]
When I add new fields to the feature service via the web map viewer, they work. Will send a map package tomorrow for testing,

![image](https://cloud.githubusercontent.com/assets/4256979/5607469/33715cfe-9412-11e4-9371-3f0e6264f9be.png)

**Comment by CTDisasterManagement** [comment]
@pjdohertygis, @driskull 

The fields Name(First Name), Last Name("Last Name"), Email("Email") are type dependent fields.If you select some value in KSA("Knowledge, Skills, Abilities") which is type field, then all of these fields will automatically populate in form.

Thanks!
