### ISSUE TITLE
Entry cannot be submitted

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#370]
When I try to make an entry with this form: http://univredlands.maps.arcgis.com/apps/GeoForm/index.html?appid=85d840e66cc64e26be8db82306bbc8ee

Using this feature service:
http://univredlands.maps.arcgis.com/home/item.html?id=b82bc53bede141a5b6f339bce644f7aa

I get this error which does not explain what is wrong. 

![image](https://cloud.githubusercontent.com/assets/4256979/5607561/b780f598-9414-11e4-9861-0346bff35b27.png)

I am able to edit that layer via the web map.

**Comment by CTDisasterManagement** [comment]
@pjdohertygis, @driskull 

We are also facing the same issue with some layers(Random Behavior), but while debugging we found that after applyEdits the response directly goes into error handler.
Also we are not getting any kind of error in console.
We will investigate the issue further and keep you updated.

Thanks!

**Comment by driskull** [comment]
Here is why it's failing.

```javascript
{"addResults":[{"objectId":null,"globalId":null,"success":false,"error":{"code":1000,"description":"Cannot insert the value NULL into column 'FirstName', table 'db_1849.user_1849.EVST250_GeoForm_v2_Class_Survey'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated."}}],"updateResults":[],"deleteResults":[]}
```

**Comment by driskull** [comment]
We shouldn't be trying to insert NULL into a column that doesn't allow nulls. However, I had put in a first name value so I'm not sure why it wasn't sending it.

**Comment by driskull** [comment]
Either we not allow them to be unchecked or any field that is not checked but is required we insert a default value of some kind. Im not sure what the best option is.

@pjdohertygis @DerrickBurke can you chime in here?

**Comment by driskull** [comment]
@CTDisasterManagement Is this issue still relevant?

**Comment by CTDisasterManagement** [comment]
Yes @driskull 
We can resolve the issue by not allowing user to uncheck the the required fields.

Thanks!

**Comment by driskull** [comment]
Ok sounds good :+1:
