### ISSUE TITLE
requiring fields bug

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#371]
1)  Open the following GeoForm application:

Geo Form Without Symbols
http://ess.maps.arcgis.com/home/item.html?id=663ec154e748421383a5183bca2b5c8e

2)  Scroll down to the bottom of the form, click on the map and then press submit.  Your form entry should go through.  Without refreshing the page, try step 2 again and notice that it will fail with requiring certain fields.
Salesforce ID: BUG-000083969
Salesforce Submitter: Alexander Nohe
Salesforce Submit Date: 12/11/2014 4:52 AM
Salesforce Bug Type: Usability
Salesforce Severity: Medium
Repro Data: (n/a)
Work Around: (n/a)
Product: ArcGIS Online
Functional Category: ArcGIS Online Application Templates
Client Platform: Windows 7
Version Found: 3.5
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by driskull** [comment]
I think this is because closest address has a default space in its  value at start. Then it gets cleared out. I think this should be fixed if we have that trim() bug fixed. #362

**Comment by driskull** [comment]
Yes, it appears this has been addressed with #362. Can you confirm @CTDisasterManagement ?

**Comment by CTDisasterManagement** [comment]
Yes @driskull this is same as #362.

First time entry is submitted because "Closet Address" has space in it.But after submission the value gets reset to EMPTY and that is the reason entry cannot be submitted.
Issue is fixed and available in Development Repository.

Thanks!

**Comment by driskull** [comment]
cool. i'll close this.
