### ISSUE TITLE
Custom Geocoder not recognized

### ISSUE THREAD

**Issue by erikkross** [Esri/geoform-template-js#372]
I entered a custom GeoCode service in the defaults.js file, but it doesn't seem to be recognized. 

"geocode": [{
            "url": "MyCustomGeoCodeURLhere"
        }]

The application still uses the default ESRI geocoder.

**Comment by driskull** [comment]
hey @erikkross,

Try something like this:

```javascript
"geocode": [{
          "url": "myUrl",
          singleLineFieldName: "Single Line Input",
          name: "My Locator",
          placeholder: "Search",
          placefinding: true
        }]
```

Then, in templateOptions.js turn "queryForOrg" to false. Otherwise, the organization geocoder overwrites the config defined one.

https://github.com/Esri/geoform-template-js/blob/master/js/templateOptions.js#L28

I think that should work.

**Comment by erikkross** [comment]
Yes, the queryForOrg seems to be the key. After setting that to false it worked fine. Thank you! 

Just in case this helps anyone else out...if you need to specify a custom geocoder and also include your organization geocoder (or give the user the option to use multiple geocoders), you can manually adjust the geocoders object that is set in the main.js file. 

In the _createGeocoderOptions function I manually added that same object you listed, after the geocoders object is created: 

```javascript
_createGeocoderOptions: function () {
    //Check for multiple geocoder support and setup options for geocoder widget.
    var hasEsri = false,
    geocoders = lang.clone(this.config.helperServices.geocode);

    //CUSTOM: called from lake-custom.js
   //this assumes there is only one object in the geocoders array
     geocoders[1] = {
        "url": "myUrl",
        singleLineFieldName: "Single Line Input",
        name: "Lake County Locator",
        placeholder: "Search",
        placefinding: true
    }

    //move custom locator to be index 0 (first) and esri to be second. 
    //another option would be to simply remove the ESRI geolocator. 
    geocoders.move(0, 1);
```

Here is what the array move function looks like: 
```javascript
Array.prototype.move = function (from, to) {
    this.splice(to, 0, this.splice(from, 1)[0]);
};
```

This is nice if you want to use a custom geocoder in addition to the default ESRI or organization geocoder.
