### ISSUE TITLE
Remember field data idea

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#380]
@julio8a proposed we have a way for the author to specify a field as "rememberable" so that it would save a cookie or local storage of what was entered for that field. The idea is that name/address/email or sorts of things like that wouldn't have to be filled out again if a user uses the form multiple times.

The cookie data would need to be based off of the unique app id and form field i suppose.

Thoughts?

**Comment by daFiter** [comment]
I think this would be nice to have. I am using a form for my call takers during emergency events. It would be nice not to have to enter in their name every time for the call taker.

**Comment by driskull** [comment]
this can be handled with default values in 4x version
