### ISSUE TITLE
Viewer mode button

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#384]
Should be like this

![screen shot 2015-01-15 at 9 08 10 am](https://cloud.githubusercontent.com/assets/1231455/5779908/7d0ac98e-9d5b-11e4-9b52-235a7abb32a4.png)

**Comment by CTDisasterManagement** [comment]
@driskull 

We are not able to see the attached image can you please share it?

Thanks

**Comment by driskull** [comment]
should be fixed now.
