### ISSUE TITLE
Ability to close info panel

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#389]
When a feature isn't selected or a user clicks on the map, the panel should be closed.  Currently, there's no way to close it and it is big at mobile sizes.

**Comment by driskull** [comment]
We should also add a close button to the top right of it so someone can close it once opened. Incase they dont know to click on the map.

**Comment by CTDisasterManagement** [comment]
@driskull 

We have added Close button, please confirm the design.

Thanks

**Comment by driskull** [comment]
Yep, looks good.
