### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#391]
Tabs have both "nav nav-tabs" and "nav nav-pills" classes. We should just be using the pills classes. The nav CSS class is also on the element twice. These should not be combined.

**Comment by CTDisasterManagement** [comment]
@driskull 

We can use "nav-pills" class in desktop mode.But if we use the same class in in small devices the navigation tabs will be shown one below the other.

Thanks!

**Comment by driskull** [comment]
If they don't fit at small size, maybe we have a menu button there instead or some UI that does fit.
