### ISSUE TITLE
Add ability to disable viewer buttons

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#393]
Incase viewer mode has bugs or someone may not want it, we should add an option to turn it off. "viewer": false. This should not show all the buttons to it and maybe even report an error if a user navigates to the page manually.

**Comment by CTDisasterManagement** [comment]
@driskull 

We are disabling the button for "Viewer Mode" if the viewer option is disable in Author mode and also showing error message if user directly goes to viewer mode.

Thanks!

**Comment by driskull** [comment]
great.
