### ISSUE TITLE
GeoForm with layer not set

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#399]
GeoForm with layer not set tries to set visibility of undefined. We should handle the error case to show an error.

http://nationalgrid.maps.arcgis.com/apps/GeoForm/index.html?appid=60307a2f86534eb987a1e47a696f0e3e&webmap=93ba0dea43f44b81a2a14372c541ddb3

``` javascript
TypeError: Cannot read property 'setVisibility' of undefined "TypeError: Cannot read property 'setVisibility' of undefined
    at declare._setLayerDefaults (http://nationalgrid.maps.arcgis.com/apps/GeoForm/js/main.js:2298:32)
    at null.<anonymous> (http://nationalgrid.maps.arcgis.com/apps/GeoForm/js/main.js:1385:22)
    at http://js.arcgis.com/3.12/init.js:177:296
    at c (http://js.arcgis.com/3.12/init.js:76:221)
    at d (http://js.arcgis.com/3.12/init.js:76:10)
    at resolve.callback (http://js.arcgis.com/3.12/init.js:77:350)
    at ha (http://js.arcgis.com/3.12/init.js:500:92)
    at Na (http://js.arcgis.com/3.12/init.js:502:60)
    at ma (http://js.arcgis.com/3.12/init.js:501:397)
    at http://js.arcgis.com/3.12/init.js:510:350"
```

**Comment by CTDisasterManagement** [comment]
@driskull 

We are setting visibility of selected layer only if layer exists.So the code will not break now.

But we need to think of the scenario when user selects "All Layer".We have only one check box in the "options" tab, how can user set visibility of multiple layers?

Thanks!

**Comment by driskull** [comment]
I guess this option would only apply when one layer is selected. We obviously don't want to make all of their layers invisible. Unless we make all of their feature layers invisible. @pjdohertygis @DerrickBurke @sTriche  what do you think?

**Comment by DerrickBurke** [comment]
@driskull it makes sense to me that we only give the visibility option when one layer is selected, not for an 'all layers' choice

**Comment by driskull** [comment]
Sounds good. @CTDisasterManagement let's:

- Disable this option when "All" is selected.
- Add to the help text "This option only applies to a single layer setup."
