### ISSUE TITLE
Automatic Date option

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#402]
In the builder for date fields, we should add an option to automatically populate the date field with the current date/time. Currently, if a user has a required date field the date will be in there already but it's kind of useless to have a fixed date. This would allow to use the current time without the user having to set it. We might want to also have a way to set it to be hidden so that a user can't change it.

**Comment by driskull** [comment]
same as #406

**Comment by nfeuerstein** [comment]
Perhaps related - though maybe a new issue: not have the default date be 1969.  The picker method works well for day and month - but changing the year from 1969 to current is quite the process.  Its easier to just manually type it in, but it feels strange to pick a day and month and then manually type in the year.
