### ISSUE TITLE
feature request: Possibility to prevent registration into future date/time

### ISSUE THREAD

**Issue by bogibrynjar** [Esri/geoform-template-js#406]
Greetings,

After using the Geoform to register measurements of Sulfur dioxide levels related to the ongoing eruption at Holuhraun (Iceland) we have noticed that it would be great to prevent registrations from being dated into the future. This can happen by mistake if for example a measurement is not registered right away using the form but later and the user inputs the wrong date/time by mistake.

Either a hard block on entering date/time values that are higher than the system time in the device used to register or a simple warning message saying that this date is in the future (or even past). This is not a serious issue but just an idea for a functionality that we have found out would be good to have to prevent date/time values in the future being registered.

Cheers!

**Comment by driskull** [comment]
Good idea. I think this relates to #402.

We should have a way to set the DatePicker field to have options. Such as:

DatePicker - Automatically set with current date/time.
DatePicker - hidden (field is not shown to user but is filled with a date or current time)
DatePicker - prevent future date/time
DatePicker - prevent past date/time

Possibly other options.
