### ISSUE TITLE
File attachments only allow image files

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#424]
Seems like we should have an option in the builder to set what type of files to allow.

**Comment by bogibrynjar** [comment]
Hi @driskull, I was looking at the commit code and wondering, because it isn't exactly clear to me, if the Geoform now supports any type of file as an attachment?

Cheers!

**Comment by driskull** [comment]
@bogibrynjar yes it should support whatever a feature layer can support.

**Comment by bogibrynjar** [comment]
@driskull thanks for the quick reply! This is a good enhancement and I guess if I want a specific file type to be available for upload I need only add it's file ending to the Feature Service property "allowedUploadFileTypes" (http://resources.arcgis.com/en/help/rest/apiref/index.html?uploads.html).

Cheers!
