### ISSUE TITLE
Add option to disable basemap toggle

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#427]
Not everyone may want to have a basemap toggle.

I would think that the basemap toggle should be opt in. The config would need a variable:

enableBasemapToggle: true

By default, it would be false.

There would need to be an option in the builder to disable it.

**Comment by coomsie** [comment]
We would be one, as the toggle option breaks our form.

We have better imagery than esri has and so use that in the form with our coord system NZTM.

I can't remove the toggle option and the user will select it making the screen blank (wrong coords for webmerc )

http://arcg.is/18hRtjM


![metroinfo_bus_stop_audit](https://cloud.githubusercontent.com/assets/125121/6458350/6eb8afb2-c1e7-11e4-988f-9cd272d59f5c.png)
