### ISSUE TITLE
Update causes form not to load due to attachement error

### ISSUE THREAD

**Issue by coomsie** [Esri/geoform-template-js#430]
I had 2 forms in arcgis.com, when i went back to use them today they both broke.

The console error was complaining about an attachment error relating to that object.

Once I went through the config wizard i noticed the attachment tick box was off and also now a new toggle option was created by default which causes issue #427

**Comment by driskull** [comment]
@coomsie nice meeting you at devsummit! This issue should be fixed, thanks for bringing it to our attention.
