### ISSUE TITLE
Select Form Fields configuration page - last column hidden by margin

### ISSUE THREAD

**Issue by srsjojo** [Esri/geoform-template-js#433]
Hey Matt,

With the latest GeoForm update the field configuration screen overruns it's container and is covered by the margin. See screenshot

![image](https://cloud.githubusercontent.com/assets/7338435/6505615/e9cb60ca-c311-11e4-9d31-7fa8e2559968.png)

Using Chrome 40.0.2214.115 m on Win7 64

Edit: Confirmed - still happens on Chrome 41.0.2272.76 m
Also happens on Firefox 36.0 and IE9 9.0.8112.16421

Thanks,
~Stephen

**Comment by driskull** [comment]
hey @srsjojo there should actually be a scrollbar at the bottom of the table so you can view the whole table. That seems to be how bootstrap handles wide tables.

http://getbootstrap.com/css/#tables-responsive

**Comment by srsjojo** [comment]
Thanks @driskull, I was setting up a very a long form and didn't see the scroll bar at the bottom. Is it possible to have the columns in the table resize to fit the container width?
