### ISSUE TITLE
Configure button no longer showing on item property page

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#434]
![image](https://cloud.githubusercontent.com/assets/4256979/6538590/1f7beb9c-c432-11e4-8ead-83ea6ed38791.png)
I don't see the see the configure button on my item property page - but I can configure the app using the using the &edit=true clause

http://arcgisforwisar.maps.arcgis.com/apps/GeoForm/index.html?appid=006cfe4efee64b18bc087d502b2d01c6&webmap=96ceb2c403a54e3caba676a47f961b7e&edit=true

**Comment by driskull** [comment]
hey @pjdohertygis. Edit the item and set it as "self-configurable". The update may have broken that part.

**Comment by driskull** [comment]
This is being fixed by arcgis online.
