### ISSUE TITLE
Support for typeahead search

### ISSUE THREAD

**Issue by coomsie** [Esri/geoform-template-js#436]
Support for typeahead search,

if the area you are search has multiple '12 Smiths Streets' and the user only thinks inside his area, they are zoomed tot he wrong location.

Typeahead would solve this ...

i.e. suggest: true set on the geocoder and the widget to support this.

Plus also the search widget should be used now instead of geocoder widget?

**Comment by driskull** [comment]
Yep, we will be implementing this. thanks!

**Comment by driskull** [comment]
same as #194.
