### ISSUE TITLE
any chance to make it hybrid ? integration with cordova? that would be awesome!

### ISSUE THREAD

**Issue by vlik** [Esri/geoform-template-js#437]

**Comment by coomsie** [comment]
I have done some work here if you wanta look ... still a bit slow ... but thats the way the app loads, which I think is under consideration.

https://github.com/CanterburyRegionalCouncil/RFS

**Comment by vlik** [comment]
cool! at least there's something to start off with!

**Comment by driskull** [comment]
very cool @coomsie
