### ISSUE TITLE
Update readme for configuring new release

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#440]
Hi @CTDisasterManagement 

A couple users noticed that the attachment settings have changed as well as layers.

Is there anything else from the readme that we need to update so that a user can configure the app without an appid?

Could you look through this section and let me know if anything is missing?
https://github.com/Esri/geoform-template-js/blob/master/README.md#configuring-defaultsjs

**Comment by driskull** [comment]
If we're no longer using these attributes, can we not save them in the appid?

```javascript
"enableAttachments": true,
    "attachmentIsRequired": false,
    "attachmentHelpText": "test2",
    "attachmentLabel": "Test",
```

**Comment by CTDisasterManagement** [comment]
@driskull,

We will remove the above mentioned properties from the config and will also check for any other useless properties lying there and send a pull request for the same.

Thanks!

**Comment by CTDisasterManagement** [comment]
@driskull,

We went through the link you provided and learnt that there are a few properties missing in it.

Below are the properties that can be included:
* defaultMapExtent
* nextBasemap
* defaultBasemap
* enableBasemapToggle
* locate

Thanks!
