### ISSUE TITLE
Tabs/pages in a form to support multiple sections/categories of questions? 

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/geoform-template-js#445]
I'm attempting to configure GeoForm to support and replace an international retail customer's PDF questionnaire for safety and security compliance. There are 13 categories of questions. Is there a way to separate these groups/categories of questions within a single  form? Perhaps a tab for each?   

There are anywhere from 1-39 questions for each of the following categories...
- Health and Safety
- Labor and Employment
- Privacy
- Consumer Protection
- Environment
- Global Ethics
- Health and Wellness
- Anti-Money Laundering
- Compliance Awareness Program
- Food Safety
- Product Safety
- Licenses and Permits
- Miscellaneous

Thanks!

**Comment by driskull** [comment]
Thanks @rfeuerstein .

relates to #365

**Comment by rfeuerstein** [comment]
Thank you!
