### ISSUE TITLE
Text field for additional information like comments or notes. 

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/geoform-template-js#446]
![form_question_comment](https://cloud.githubusercontent.com/assets/7117658/6815389/5851daae-d246-11e4-9db6-36db729f9288.png)
I have a PDF form that I'm attempting to mirror with GeoForm and in addition to a radial option of yes or no provides a "comments" section to capture text notes for each question, see attached. Is this something you've seen before? Any suggestion on how to meet this workflow requirement with GeoForm? Thank you.

**Comment by driskull** [comment]
Probably just have a text area field below the question that is optional.

**Comment by driskull** [comment]
duplicate of #515
