### ISSUE TITLE
Builder field Issue

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#451]
1. This field column is too wide. It's taking up too much space.
2. The help text says "viewerMode". Please replace anything that says viewer mode with just "viewer".
3. Do a find for any "viewerMode" or "viewer Mode" text and update it.

![screen shot 2015-03-26 at 10 27 21 am](https://cloud.githubusercontent.com/assets/1231455/6852608/e674963e-d3a2-11e4-9c98-132df6da2134.png)

Thanks!

**Comment by driskull** [comment]
Also, those column headers have a class of "radio" for some reason and its making them.

It has a label tag in there too which is messing it up.

**Comment by CTDisasterManagement** [comment]
@driskull,

We have replaced "viewerMode" or "viewer Mode" to "viewer"(Excluding all NLS files other than english).
If we use "tableDimension2" class to "Display Field" column it will look like:
![display-field](https://cloud.githubusercontent.com/assets/5261405/6865076/0a5ae858-d490-11e4-987c-2cd2a2fc69ad.jpg)

Please let us know ur feedback.

Thanks!!

**Comment by driskull** [comment]
thanks!

Can we have it say:

"Selected display field will be shown in the viewer as a title".
