### ISSUE TITLE
Fields showing up twice in app

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#452]
Fields showing up twice in this app.

?appid=be338760de9249f8b15df22a8e4ee586

![screen shot 2015-03-26 at 10 31 11 am](https://cloud.githubusercontent.com/assets/1231455/6852666/3c2bfb1c-d3a3-11e4-9163-c01bf2cbb932.png)

**Comment by driskull** [comment]
It seems like all the fields are showing up twice for some reason.

**Comment by CTDisasterManagement** [comment]
@driskull,

Although fields are showing up twice in given app id, but we are not able to reproduce the same issue with other app id's.
Can you please share the steps to reproduce so we can look into it in detail.

Thanks!!

**Comment by driskull** [comment]
@CTDisasterManagement I'm not sure what happened. I just added this layer to the existing app when it was in all layer mode and then set all the domains to filter select.

http://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/APHAMobileDataV4/FeatureServer/0

Can you investigate the app json and use it to figure out what is causing it?

http://www.arcgis.com/sharing/rest/content/items/be338760de9249f8b15df22a8e4ee586/data?f=json

**Comment by CTDisasterManagement** [comment]
Sure @driskull we will look into it and keep you updated.

**Comment by driskull** [comment]
thanks!

**Comment by CTDisasterManagement** [comment]
@driskull 

We analysed the given app json and we found a 'length' property in fields objects that was causing this issue.
The issue is resolved and we will send a pull request soon.

Thanks!!

**Comment by driskull** [comment]
Awesome. thanks for investigating.

**Comment by CTDisasterManagement** [comment]
@driskull,

Although the above issue is fixed but due to changes in plugin files in vendor folder(DatePicker,Select2 etc..) code is breaking in some scenarios.
We are trying to find the cause and will keep you updated.

Thanks!!

**Comment by driskull** [comment]
@CTDisasterManagement ok. I'm not seeing anything broken. It may be a merge issue?

**Comment by CTDisasterManagement** [comment]
@driskull,

Code breaks when form has "Date" and "Filter Select" fields.

Date Field:
setDate, setMaxDate and setMinDate from bootstrap Date Picker are deprecated.

Select2:
'val' property from Filter Select is also deprecated.

Do you want us to make the necessary  changes and send pull request ?

Thanks!!

**Comment by driskull** [comment]
Yes please if you can. Otherwise, I can probably handle it. Thanks @CTDisasterManagement

**Comment by CTDisasterManagement** [comment]
@driskull,

We will update the code and send new pull request soon.

Thanks!!
