### ISSUE TITLE
Wrong dateFormat in localization files

### ISSUE THREAD

**Issue by sverker84** [Esri/geoform-template-js#457]
We have discovered that the dateFormat for the bootstrap-datetimepicker is wrong in certain languages. For example, Swedish (sv), Dutch (nl) have an incorrect dateFormat in their respective resources.js file. These files are located in /js/nls/xx/resources.js where xx is the locale short name.

I have found that the bootstrap-datetimepicker documentation, http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#format references http://momentjs.com/docs/#/displaying/format/ so all dateFormat strings should conform to this standard.

This also affects the GeoForm webapp in ArcGIS Online

**Comment by driskull** [comment]
thanks @sverker84 we'll get it fixed.
