### ISSUE TITLE
When I copy and paste HTML code into the Details page - every time I hit Preview or Publish, it duplicates the entry.

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#460]
I followed the steps for embedded a Google Translate toolbar on my app. Link: https://translate.google.com/manager/website/suggestions

![image](https://cloud.githubusercontent.com/assets/4256979/7261311/b9fe85dc-e83e-11e4-8b22-7b8155c148d4.png)

All I did was - 

1) Paste it into the Details Form and Instructions "Code-View" 
2) Justified the bar to the right 
3) Hit Preview
4) Change something else
5) Hit Preview or Publish again 

I end up with a duplicate bar on my app and duplicate HTML in the Code-View.

**Comment by pjdohertygis** [comment]
Here here is a screenshot screenshot : )

![image](https://cloud.githubusercontent.com/assets/4256979/7261368/30b3f8ce-e83f-11e4-8ada-0b9a35980674.png)

**Comment by driskull** [comment]
@pjdohertygis I don't think this will work correctly when put in here. Part of it is supposed to go into the head of the document and the other in the body. You would probably need to put it in the index.html file and host the app yourself for this to work correctly. 

I'll look into it though.

**Comment by pjdohertygis** [comment]
Actually - it seems to be working. Give it a try!
http://pjdohertymaps.maps.arcgis.com/apps/GeoForm/index.html?appid=630c8f4e8d634dd9a75c423338cbd86d

However - if I save and publish or preview - it duplicates the code : (

**Comment by driskull** [comment]
The issue is with summernote handling the JavaScript. although its also a problem with the google script.

When the script is being run, it's creating another HTML element.

Same thing happens here: http://summernote.org/#/

When the html button is closed, the script is ran and another element is created.
