### ISSUE TITLE
Feature requests: hide unnecessary fields and make fields mandatory

### ISSUE THREAD

**Issue by darinacosta** [Esri/geoform-template-js#464]
Hello there!

I'm a GIS analyst at the City of New Orleans. I modified our geoform to suit a specific use case, and one of our ESRI contacts suggested that I submit a pull request for these changes. 

Our branch includes 2 additional field configuration options in the default config. One is intended to hide unnecessary fields from the user; and the other allows users to add the "mandatory" class to fields. More details are available in the comment of the [pull request](https://github.com/Esri/geoform-template-js/pull/463). Forgive me if I submitted the request prematurely! I'm opening this issue now in case there are any questions regarding these features.

**Comment by driskull** [comment]
Hey @darinacosta thanks so much. :+1:  I saw this but haven't had the chance to look into it yet.

I think this will be a good enhancement but it may be modified at some point in the future. We'd like to support a cascading decision tree that is more than just one level deep but that's going to require more development and design. This looks like a simpler solution for the time being.

I'll work on getting it merged in.

**Comment by driskull** [comment]
Will add this in 4x version
