### ISSUE TITLE
Configuration Option to disable Social Media Icons/Sharing

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/geoform-template-js#465]
Customers in the Intelligence Community, Law Enforcement, and Defense do the majority of their work on internal or separate networks which do not have social media.  It would be less distracting if there was an option to disable the icons for sharing on social media.

**Comment by driskull** [comment]
hey @nfeuerstein. There actually is an option for this but maybe it needs to be reworded or made more clear. I'll make some text changes to be more specific. 

![screen shot 2015-05-21 at 8 58 57 am](https://cloud.githubusercontent.com/assets/1231455/7753023/adecfaf6-ff97-11e4-8146-bb7974ff7b09.png)

**Comment by driskull** [comment]
How does this sound?

![screen shot 2015-05-21 at 9 04 16 am](https://cloud.githubusercontent.com/assets/1231455/7753152/6d29d5c4-ff98-11e4-9117-0e9db4f0f63f.png)
