### ISSUE TITLE
GeoForm template doesn't respect custom fields configuration

### ISSUE THREAD

**Issue by jbailey-spatialbridge** [Esri/geoform-template-js#473]
defaults.js provides for the ability to customize the set of fields displayed in the GeoForm, via the "fields" setting.

However, this customization is overwritten at approximately line 2668 in main.js:

```javascript
this.config.fields[this.config.form_layer.id] = this.map.getLayer(this.config.form_layer.id).fields;
```

The custom fields defined in defaults.js are replaced by the default fields for the layer.

This can be corrected by commenting this line out. Perhaps this line should only be executed if there's an error in the fields setting.

**Comment by driskull** [comment]
Thanks @jbailey-spatialbridge.

If you wrap it in an if statement like this, does it work correctly for you?

```javascript
if(!this.config.fields.hasOwnProperty(this.config.form_layer.id)){
                this.config.fields[this.config.form_layer.id] = this.map.getLayer(this.config.form_layer.id).fields;
              }
```
