### ISSUE TITLE
Date Time Picker Config

### ISSUE THREAD

**Issue by gardneg** [Esri/geoform-template-js#474]
My users would like to be able to type or paste a date in MM/DD/YYYY format into the form then tab to the next line. When they try this now the calendar automatically opens as soon as the field is tabbed to and instantly typing does not clear the date. If the field is cleared and a date entered manually as MM/DD/YYYY the picker sets the date incorrectly. Example manually entered 8/20/2015 and the picker changed it to January 8, 0020 8:15 AM.

I would like to see an option to configure the date time picker in the following ways:
1) be able to set-up how the date is displayed
2) allow entry without using the calendar control.

**Comment by driskull** [comment]
hey @gardneg the way the date is currently displayed depends on the user's locale. So someone from another country get's the format appropriate for that country.

I'm adding formats to allow entering dates as you proposed. It doesn't seem to let me allow time though.

96fd026adbbf2b794a47bd912d98ae6dd72f18a6
