### ISSUE TITLE
How to display attachment in pop-up window automatically?

### ISSUE THREAD

**Issue by mariof247** [Esri/geoform-template-js#475]
Hello,

Maybe this is a newbie question, but I would like to know if it's possible to display an attachment in a pop-up window automatically, by configuring the pop up windows? If so, how can it be done?

The purpose is for the user to fill in the Geoform, attach a picture, and then, in the layer which the information is submited, the popup would display the picture and not the link to the picture.

Thank you in advance!

**Comment by driskull** [comment]
Hi @mariof247 I don't think that's possible at this time. Attachments are always displayed as a link. :(
