### ISSUE TITLE
On entry submission report back a value(s) from the newly added feature

### ISSUE THREAD

**Issue by amarinelli** [Esri/geoform-template-js#478]
Enhancement Request, might be a specific use case...

When an entry is successfully submitted, a dialog appears which reports this to the user, provides a share link, and view submission web app button link.

It could be incredibly useful to use this screen to report back on a field from that submitted record.  It could be a unique id, a status field, etc.

The use case is when a database trigger assigns a unique id to the record when it is created.  Reporting this back to the user could provide a reference number or piece of information useful for finding that feature in the future or linking to it.

Optionally, some or all of the field values could be formatted and shown in the dialog so the user can review them one last time or recall what they just submitted.

Quick example:

![image](https://cloud.githubusercontent.com/assets/4150021/10060691/c7852510-6220-11e5-83df-f96dc913b2cb.png)

**Comment by driskull** [comment]
How about a custom template string that could be set by the author?

Like:

```
"You rated the GeoForm {field_stars} stars!"
```

**Comment by amarinelli** [comment]
That would be perfect, thanks @driskull!

**Comment by driskull** [comment]
this will be handled by #513 and #501
