### ISSUE TITLE
Ability to download photos with feature layer service

### ISSUE THREAD

**Issue by geotrek** [Esri/geoform-template-js#481]
It looks like the photos are stored server side in ESRI's cloud. How can I get access to these photos? If I share my app within my organization only, these photos are NOT publicly available right?
I would like to download these photos via export to shapefile from the feature layer used in geoform.

**Comment by driskull** [comment]
@geotrek I think using an open data portal with the service should allow that. It's probably not something we would do on the geoform itself.

**Comment by geotrek** [comment]
Ok. So, I exported ESRI's feature service to GeoJSON and still the "Photo": null. The photos are null in geoforms view submission web map as well. Is this by design? The only place you can view the photos is on the web map you created in arcgis.com to build the geoform app. off of.

**Comment by driskull** [comment]
The photos are actually stored as attachments in the Feature Layer. So they aren't just a URL or a property in the attributes. I think I have an issue on here to allow viewing attachments of features on the GeoForm webmap, just haven't gotten to it yet.
