### ISSUE TITLE
Issue when viewing pop-up on View Submissions map (trim is not a function)

### ISSUE THREAD

**Issue by amarinelli** [Esri/geoform-template-js#482]
`TypeError: Object doesn't support property or method 'trim'`

![geoform-ie-error](https://cloud.githubusercontent.com/assets/4150021/10525770/a53db93c-7354-11e5-8411-850655cde7c3.png)

**Comment by driskull** [comment]
thanks @amarinelli . Can you try replacing with string.trim and let me know if that fixes it. It should have support for handling .trim()

**Comment by amarinelli** [comment]
This does not appear to be browser specific.  Same issue just happened on Chrome (latest).

`a.trim is not a function`

**Comment by amarinelli** [comment]
@driskull I am using the hosted version from arcgis.com

**Comment by driskull** [comment]
@amarinelli is your app public? if so, could you share it's appid?

**Comment by amarinelli** [comment]
Currently the app is private and using only internally accessible features from AGS.  Previous GeoForms I have made do not exhibit same issue.  Just recreated one using different feature data and it worked fine.

In the app with issue, the display field and sort field for the View Submissions map is an Integer.  I just noticed your commit for 'only trim strings'.  Do you think the issue could be related to the field data type?

**Comment by amarinelli** [comment]
If I click a point which has a <null> value for the (integer) sort field....then the pop-up appears without the 'trim' error.

**Comment by driskull** [comment]
@amarinelli Yes, I think it has to do with the type.

**Comment by amarinelli** [comment]
@driskull: confirmed using test data that 4572e77f51607c515ce1fcff62ecada61cdc9b45 fixed the issue. Thanks!

**Comment by driskull** [comment]
awesome thanks
