### ISSUE TITLE
The Viewer displays date fields with null values as 12/31/1969, 7:00:00 PM

### ISSUE THREAD

**Issue by amarinelli** [Esri/geoform-template-js#483]
The Unix Epoch time (`12/31/1969, 7:00:00 PM`) is displayed instead of just a blank or _null_ value. In the web map and database, these values are actually _null_ and display as such.

![viewer-date-error](https://cloud.githubusercontent.com/assets/4150021/10645520/25b8f332-77fc-11e5-9a68-ca0f89755e4b.png)
.

**Comment by driskull** [comment]
thanks @amarinelli can you verify the fix?

**Comment by amarinelli** [comment]
@driskull: confirming using test data that ed10be35468bea2cc4325bfde369be5274352542 fixed the issue.  Thanks!

**Comment by driskull** [comment]
:+1:
