### ISSUE TITLE
Attribute table pop-up of View Submissions map uses domain CODE and not the DESCRIPTION

### ISSUE THREAD

**Issue by amarinelli** [Esri/geoform-template-js#487]
Web map
![image](https://cloud.githubusercontent.com/assets/4150021/11445460/3ccc2312-94fa-11e5-8094-dc1d50f124b9.png)

GeoForm
![image](https://cloud.githubusercontent.com/assets/4150021/11445470/4d84fff8-94fa-11e5-95cf-122789e6f324.png)

**Comment by driskull** [comment]
67bf4a9611e98b53339043a6fc74392b48c6d1e4
