### ISSUE TITLE
Geoform not using proxy (to access private hosted service)

### ISSUE THREAD

**Issue by jakc** [Esri/geoform-template-js#488]
How can I get a public geoform to feed into a private feature service without asking the user for credentials?  I assume the answer would be through Application Authentication.  
 
I downloaded geoform, deployed to S3.
I registered this app with ArcGIS Online to get a key/secret.
I added this appid to the default.js in geoform:
"oauthappid": "11111111111111",
 
I have added a link to my proxy  in default.js:
"proxyurl": "http://testmachine/mwproxy/proxy.ashx",

However, when hitting the app, it does not appear to apply the proxy.  Have I missed something obvious?

**Comment by driskull** [comment]
Sounds correct, did you add a proxyRule?
 
Sounds like you just need to do that.
 
https://developers.arcgis.com/javascript/jsapi/esri.urlutils-amd.html#addproxyrule

Here's an example:
https://gist.github.com/driskull/4917adc87acf1d8c613d

**Comment by jakc** [comment]
I apply this proxy rule within index.html and not viewer.html?
Still does not appear to be pushing requests via proxy.  Is there a useProxy setting I need to apply outside of the config?

```javascript
myTemplate.startup().then(function (config) {
				urlUtils.addProxyRule({
                urlPrefix: "http://services1.arcgis.com/vHnIGBHHqDR6y0CR",  // Does this look right? This is what worked when testing with AppBuilder
                proxyUrl: config.proxyurl
				});
```

Proxy:
```javascript
<serverUrl url="http://esriau.maps.arcgis.com/"
					clientId="myclientid"
					clientSecret="mysecret"
					oauth2Endpoint="https:/theorg.maps.arcgis.com/sharing/oauth2"
					rateLimit="600"
					rateLimitPeriod="60"
					matchAll="true"/>
```

**Comment by driskull** [comment]
I think you can get rid of the `http://`. Maybe just try `s1.arcgis.com/vHnIGBHHqDR6y0CR`. It should then direct all traffic to that URL through the proxy. If it's not, then it isnt matching the URL correctly.

**Comment by jakc** [comment]
Beuatiful.  Works as expected.  Thanks

**Comment by driskull** [comment]
awesome :+1:
