### ISSUE TITLE
Customize the 'Submit a Report'/'Submit Entry' dialogue

### ISSUE THREAD

**Issue by brianjbaldwin** [Esri/geoform-template-js#490]
I have been getting pinged that people want to have a more 'custom' look in the viewer mode.  One thing that would go a long way is just providing a dialogue to allow someone to customize this button.

It would be good to have it consistent across both pages as well, currently, the GeoForm submission area says "Submit Entry /  View Submissions" while the Viewer has "Submit a Report"

**Comment by craygo69** [comment]
You can change these buttons by editing the js/nls/resources.js file.
line 64 changes the "Submit Entry" text
line 124 changes the "View Submissions" text
line 276 changes the "Submit a Report" text

There is also a "View Submissions" on line 261 but have not found it in the application

Not a fix for changing these while configuring the app but can do this as a workaround for now.

Hope this helps

Ray
