### ISSUE TITLE
unable to create map: form layer does not exist

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#491]
The Mountain Rescue Association is filling out a GeoForm and getting this "error: unable to create map: form layer does not exist". 

This has been confirmed by multiple people - I will gather more information on their device. Any ideas?

Here is a GeoNet post that describes similar symptoms: https://geonet.esri.com/thread/170430

**Comment by driskull** [comment]
Most likely, the layer that it was configured with was removed from the webmap or the layer is is not a feature layer.

**Comment by pjdohertygis** [comment]
Negative - confirmed it is in the web map and works for me as an admin but not for two users (so far).

However - how about if it were a feature layer Shared with and Organization but also with a Group that were not members of?

**Comment by pjdohertygis** [comment]
One person has the following configuration. 

1 - On a PC 
2 - Chrome

I am only receiving the error, when I click the tab "enter a new mission".

The other: 
1.  Mac
2. Chrome

**Comment by pjdohertygis** [comment]
Ok - it appears the issue was resolved when I added these two people to a Group where the service, web map, and app were stored.

But they were shared with the Organization and they were members of this Organization.

Interesting - so probably not a bug but I'd suggest an enhancement for a more descriptive error message so Users know how to fix it.

**Comment by driskull** [comment]
Thanks, I'll adjust for the confusion.
