### ISSUE TITLE
Error on gpx file attachments upload to a AGOL hosted feature service via Geoform

### ISSUE THREAD

**Issue by bogibrynjar** [Esri/geoform-template-js#492]
**UPDATE:** *GPX file uploads work with on premise Feature Service when added to the "AllowedUploadFileTypes" property of the service.*

Been testing out uploading other file formats as attachments via a on premises hosted Geoform since this should be supported now (see issue #424). Image and movie files work (as long as they are less than 25mb) but I'm getting an error on gpx files. I suspect this is because the hosted feature service does not support this file type. 

I've gone into the Services REST admin to try to see if this can be modified but can not seem to get into the "Uploads" section where there is suppose to be a property to change supported file formats. Maybe this isn't even possible with hosted feature services? 

This is not really an issue or enhancement request, just reporting my findings here to the devs and anyone else who might be interested. Going to try this on a feature service hosted on premise next and see if I can get it to work then.

Cheers!

**Comment by driskull** [comment]
Thanks @bogibrynjar. This should be helpful for anyone who needs more info on it.
