### ISSUE TITLE
Ability to see the attachments in "View Submissions" map view popup

### ISSUE THREAD

**Issue by BennyBaruba** [Esri/geoform-template-js#493]
I would like to see the option to config the visibility of the attachments in the "View Submissions" map view.  The user of the app can add the attachments just fine.  However when they look at the submissions in the "View Submissions" map view, there is no option to look at the attachments.  The following link is the app we are planning to use at an upcoming hackathon... http://arcg.is/1nEnWcy

**Comment by r3weber** [comment]
I would love to see this added as well.

**Comment by r3weber** [comment]
Here is my form: http://arcg.is/1TuGnxp

**Comment by driskull** [comment]
Will fix this in 4x version
