### ISSUE TITLE
Darkly Date Picker - not visible

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#494]
![image](https://cloud.githubusercontent.com/assets/4256979/13087642/d4abf0a8-d49d-11e5-9cff-4cf94c052142.png)

The date picker when using the Darkly theme is very difficult to use because numbers are "blacked out". I recognize that these themes come from Bootstrap, but perhaps there is something that can be done to improve this in future releases.

**Comment by pjdohertygis** [comment]
NOTE: in the image above, the configuration is 

![image](https://cloud.githubusercontent.com/assets/4256979/13087909/d644a076-d49e-11e5-8b7a-d4fa86f7be95.png)

**Comment by driskull** [comment]
should be fixed next release
