### ISSUE TITLE
Viewer login pop-up window not rendering correctly (secure feature service)

### ISSUE THREAD

**Issue by sudhir449** [Esri/geoform-template-js#495]
The login window does not render properly when viewing the submitted records of a secure feature layer. 
[http://esri.github.io/geoform-template-js/viewer.html?webmap=62686b3ffd1042e494479f6fcec9ba7c](http://esri.github.io/geoform-template-js/viewer.html?webmap=62686b3ffd1042e494479f6fcec9ba7c)

Attached is a screenshot.
![image](https://cloud.githubusercontent.com/assets/7605676/13310216/ae626a3c-db49-11e5-87c5-0ec8791f14c3.png)

**Comment by driskull** [comment]
Thanks @sudhir449. Should be fixed online next week.

**Comment by sudhir449** [comment]
Matt - thanks for looking into this. It has fixed the styling on the login pop-up window, but now appears to cause some issue on how the page is displayed after logging in, especially the padding around the borders and the submit button is displayed only partially. Attached is a screenshot.
![image](https://cloud.githubusercontent.com/assets/7605676/13337548/9eb81f3a-dbe1-11e5-911c-3ef9e6a1c505.png)

**Comment by driskull** [comment]
Thanks @sudhir449 . I think it should be good now.

**Comment by sudhir449** [comment]
Thanks Matt.
