### ISSUE TITLE
Form Layer Does not Exist

### ISSUE THREAD

**Issue by yeonkim** [Esri/geoform-template-js#497]
Hello,

I have a geoform set up to collect registrations. The geoform  template was downloaded (back in January), and was set up to connect to a web map. 
It works fine till I try to set up a "form_layer". There is only one feature service in the web map, but I wanted to check if it honors my form_layer id before setting custom fields. As soon as I populate form_layer with my layer ID, it complains that 'Form Layer does not Exist'. Even when I set "id": "ALL", it comes back with the same error message 'Form Layer Does not Exist'.

I also tried leaving my form_layer variable blank and proceeding with setting custom fields (using the same form layer ID!). I listed all the editable attributes, but only those attributes that are not required are showing up in the form with my customization.

Any pointers and suggestions are greatly appreciated. Maybe someone would be willing to share a  working default.js (for a public geoform) that is set up with "form_layer" and "fields"?

Thank you.
Yeon

**Comment by driskull** [comment]
hey @yeonkim try using:

```
form_layer: {
id: "all"
}
```

Are you sure the layer is pointing to a feature service and not a map service?

**Comment by yeonkim** [comment]
Thanks, Matt! id:"all" did the trick and now it is asking me to select a form. Maybe we need to update the line in the 'Readme. md' file?

And yes, I am using a feature service linked in a web map.

I am still having issues showing all the attributes. None of the required attributes are showing when I use custom fields in default.js. Only optional attributes are showing in the form. Any suggestions? Maybe I should make all the fields optional and see if the missing ones show up.

Thank you for all your help!
Yeon

**Comment by driskull** [comment]
Awesome. Just renamed it so others don't have the same issue. Thanks @yeonkim !
