### ISSUE TITLE
geocoder service

### ISSUE THREAD

**Issue by teckey** [Esri/geoform-template-js#500]
changing the goecoder service url has no effect. still defaults to esri world locator.

**Comment by driskull** [comment]
hey @teckey , how are you changing it?

**Comment by teckey** [comment]
hello @driskull thanks for the reply and sorry for me just now getting back to it.
I was changing it in the SearchSources.js line 72. 
I would really appreciate it if you can point me in the right direction. Thanks in advance!

**Comment by driskull** [comment]
hey @teckey,

So, if you set the `queryForOrg` to `false` in the [templateConfig](https://github.com/Esri/geoform-template-js/blob/master/config/templateConfig.js#L28) then you should be able to set the geocode URL in the [config](https://github.com/Esri/geoform-template-js/blob/master/config/defaults.js#L77)

```js
//When true the template will query arcgis.com for default settings for helper services, units etc. If you
  //want to use custom settings for units or any of the helper services set queryForOrg to false then enter
  //default values for any items you need using the helper services and units properties.
  "queryForOrg": true,
```

Otherwise, it will grab all the services from the organization and overwrite what you have set in the config.

Or, you could overwrite these options from main.js or anywhere after the template.js code has been run.  That would be a good time to modify anything in `this.config.helperServices` to make changes you want. Just remember to do it before the search widget is created.

Somewhere in the top of [this function](https://github.com/Esri/geoform-template-js/blob/master/js/main.js#L2107) would be good.

Let me know if that gets you where you need.

-Matt

**Comment by teckey** [comment]
@driskull ,

I have changed the lines you have pointed out.. Now the search yields no results. 

` "queryForGroupItems": false,
.`

`        "geocode": [{
            "url": "http://maps.evansvillegis.com/arcgis_server/rest/services/GEOCODERS/Parcels_WGS84_Locator/GeocodeServer"
        }]`

**Comment by driskull** [comment]
hey @teckey, its actually `queryForOrg`.

**Comment by teckey** [comment]
lol sorry copied the wrong line to paste. I actually changed the value you suggested.

templateConfig

`define({
  // When true, the template will query arcgis.com for the webmap item.
  "queryForWebmap": true,
  // When true, the template will query arcgis.com for the group's information.
  "queryForGroupInfo": false,
  // When true, the template will query arcgis.com for the items contained within the group
  "queryForGroupItems": false,
  //When true the template will query arcgis.com for default settings for helper services, units etc. If you
  //want to use custom settings for units or any of the helper services set queryForOrg to false then enter
  //default values for any items you need using the helper services and units properties.
  "queryForOrg": false,
  //If you need localization set the localize value to true to get the localized strings
  //from the javascript/nls/resource files.
  //Note that we've included a placeholder nls folder and a resource file with one error string
  //to show how to setup the strings file.
  "queryForLocale": true,
  // support sending credentials with AJAX requests to specific domains. This will allow editing of feature services secured with web-tier authentication
  "webTierSecurity": true,
  // These are the options specified for querying items within the group. Modify these to get more items. You can also call the public template.queryGroupItems() method with these options as a parameter.
  "groupParams": {
    q: "group:\"${groupid}\" AND -type:\"Code Attachment\"",
    "sortField": "modified",
    "sortOrder": "desc",
    "num": 9,
    "start": 0
  },
  //This option demonstrates how to handle additional custom url parameters. For example
  //if you want users to be able to specify lat/lon coordinates that define the map's center or
  //specify an alternate basemap via a url parameter.
  "urlItems": [
    "edit",
    "locate",
    "search",
    "latlon"
  ],
  // For esri hosted envoronments only. Will automatically create a sharingurl and proxyurl for the application.
  esriEnvironment: true
});`

default.js

`define({
    //Default configuration settings for the applciation. This is where you"ll define things like a bing maps key,
    //default web map, default app color theme and more. These values can be overwritten by template configuration settings
    //and url parameters.
    "appid": "fbb4ad21436b4fcea49f86ba67b4b01a",
    "webmap": "406606f13a2e4dfbbeea0cf477c7303f",
    "form_layer": {
        "id": ""
    },
    "details": {
        "Title": "",
        "Logo": "",
        "Description": ""
    },
    "fields": {
		
    },
    "theme": "basic", // see values in themes.js
    "oauthappid": null,
    //Enter the url to the proxy if needed by the applcation. See the "Using the proxy page" help topic for details
    // //developers.arcgis.com/en/javascript/jshelp/ags_proxy.html
    "proxyurl": "",
    //Example of a template specific property. If your template had several color schemes
    //you could define the default here and setup configuration settings to allow users to choose a different
    //color theme.
    //Enter the url to your organizations bing maps key if you want to use bing basemaps
    "bingmapskey": "",
    //Defaults to arcgis.com. Set this value to your portal or organization host name.
    "sharinghost": location.protocol + "//" + "evansvilleapc.maps.arcgis.com/",
    "units": null,
    "useSmallHeader": false,
    "enableSharing": true,
    "defaultMapExtent": true,
    "pushpinColor": "blue",
    "nextBasemap": "hybrid",
    "defaultBasemap": "topo",
    "selectedTitleField": {},
    "disableViewer": false,
    "enableAttachments": true,
    "attachmentIsRequired": false,
    "attachmentLabel": "",
    "attachmentHelpText": "",
    "showLayer": true,
    "disableLogo": false,
    "enableBasemapToggle": false,
    "enableOfflineSupport": true,
    "locate":false,
    "locationSearchOptions": {
        "enableMyLocation": true,
        "enableSearch": true,
        "enableLatLng": true,
        "enableUSNG": false,
        "enableMGRS": false,
        "enableUTM": false
    },
    "locationSearch": true,
    //When searchExtent is true the locator will prioritize results within the current map extent.
    "searchExtent": false,
    "searchLayers":[{
        "id": "",
        "fields": []
    }],
    "attachmentInfo":{
    },
    "submitButtonText": "",
    "viewSubmissionsText": "",
    "helperServices": {
        "geometry": {
            "url": null
        },
        "printTask": {
            "url": null
        },
        "elevationSync": {
            "url": null
        },
        "geocode": [{
            "url": "http://maps.evansvillegis.com/arcgis_server/rest/services/GEOCODERS/Parcels_WGS84_Locator/GeocodeServer"
        }]
    },
    "bitlyLogin": "arcgis",
    "bitlyKey": "R_b8a169f3a8b978b9697f64613bf1db6d"
});`

**Comment by driskull** [comment]
Hey @teckey, sorry about that.

It looks like if you put this along with `queryForOrg: false` it should work correctly:

```
"helperServices": {
        "geometry": {
            "url": null
        },
        "printTask": {
            "url": null
        },
        "elevationSync": {
            "url": null
        },
        "geocode": [{
            singleLineFieldName: "Single Line Input",
            "url": "http://maps.evansvillegis.com/arcgis_server/rest/services/GEOCODERS/Parcels_WGS84_Locator/GeocodeServer"
        }]
    },
```

**Comment by teckey** [comment]
@driskull Thank you sir! that did the trick.
