### ISSUE TITLE
Viewer page does not display Date values properly

### ISSUE THREAD

**Issue by rmangan** [Esri/geoform-template-js#502]
Using a date field as the display field for the view submission pages results in "Invalid Date" being displayed in the Viewer page. 

I am using a pre-existing dataset as the collection layer, is it possible this is the issue?

**Comment by driskull** [comment]
Should be fine. Can you share the layer so I can use it to test?

**Comment by rmangan** [comment]
Sure, 

Here's the layer being used:
http://hartgis.maps.arcgis.com/home/item.html?id=f24cf3c940f243aa942a2dd754937eb0

Here's our geoform:
http://hartgis.maps.arcgis.com/apps/GeoForm/index.html?appid=aef8c50820914d178c48d16bbb87a6d8

I had to remove client data from the layer and republish, but the new geoform is displaying the same functionality on the viewer page (not use field alias for field name, not changing list when a different field is selected)

Additionally the geofrom builder page did not prompt me to select a display field for the viewer page.

**Comment by driskull** [comment]
Got it fixed but it won't be on arcgis.com until our next deployment.

Thanks for reporting it!

**Comment by rmangan** [comment]
Awesome, thanks!
