### ISSUE TITLE
Custom fields with a required attribute, which has domain

### ISSUE THREAD

**Issue by yeonkim** [Esri/geoform-template-js#505]
As I reported previously in #497 , I had some required fields not showing up properly when I tried to customize them in default.js. After trial and error, I found out that a required attribute field which had domain values were not happy being 'customized' and wouldn't show up. Once I made this field not required (Allow NULL values = Yes in feature class properties), it showed up on the form.

Just wanted to share in case someone else runs into the same issue.

Thanks. Yeon

**Comment by driskull** [comment]
thanks @yeonkim.
