### ISSUE TITLE
Successful login does not set cookies

### ISSUE THREAD

**Issue by nobleach** [Esri/geoform-template-js#507]
I have hosted this template on a 3rd party domain. My issue is every time I refresh the page, I have to log in again. I do see the call to generateToken. This does return a token with an expiration of 60 minutes. I don't see where this is getting persisted in the code however. (I'm assuming IdentityManager)

**Comment by driskull** [comment]
Hey @nobleach 

I think the best way to achieve that would be to use oAuth.

Here are some helpful resources:

https://developers.arcgis.com/authentication/signing-in-arcgis-online-users/
https://developers.arcgis.com/javascript/3/jshelp/ags_secureservices.html
https://developers.arcgis.com/authentication/
