### ISSUE TITLE
fields don't show and then re-order (inserted first) after subtype is picked

### ISSUE THREAD

**Issue by tchristo** [Esri/geoform-template-js#509]
When I use subtypes in a geoform, any fields that have a default value dependent on subtype value, will show up first regardless of the field ordering specified in the geoform builder. Haven't fully tested across platforms/browsers but this happens on a Window PC in IE11.

I see this was a recent comment by "fnprice" on the GeoForm Grad blog (https://blogs.esri.com/esri/arcgis/2014/09/25/the-geoform-graduates/) but no one else has commented on this behavior.

If this can't be fixed I see 2 options for a workaround:
Reset my feature class to not use any defaults
Reset my feature class so that all fields have defaults

I'm sure this is related, so I'll say that, depending on the number of fields with subtype-dependent defaults, it is a little startling for a user to see only a few fields when they first open a geoform page and then only after they select a subtype, do these 10 extra fields show up (and out of order).

**Comment by driskull** [comment]
Hey @tchristo,

If the subtype has templates, then it needs to show before the fields that it effects so that a user doesn't fill out information that will get reset by the domain's template.

I think that is what you're running into.
