### ISSUE TITLE
Ability to use a non-geographic feature table as the form layer

### ISSUE THREAD

**Issue by etes** [Esri/geoform-template-js#510]
Is there a possibility to add a non-geographic feature table layer as the form layer? 
I would like to be able  to register new row of a related table record using this form template. But the error below shows up when i declare the "form_layer" with the id of the table layer in the config file.

"form_layer": {
        "id": "skjenkesteder_8707"
    },

Error message: "**Unable to create map: A valid layer to create the GeoForm was not found. If the GeoForm has been configured with a layer, the layer may no longer be available, or authorization failed.**"

![error_message](https://cloud.githubusercontent.com/assets/446407/16481885/ad35eaf4-3ead-11e6-8d2a-00d9601266b8.png)

**Comment by driskull** [comment]
Not currently, but we can add that to the queue

**Comment by mkettouche** [comment]
also to Ability to use a non-geographic feature table as the form layer, if non geographic  feature **table is related to feature classe** is it possible to **select feature from it,**(related feature classe) to maintien relationship of the new record submited with the form ? 
like an other way to "Crowdsource Polling" application template ([http://solutions.arcgis.com/local-government/help/crowdsource-polling/]

**Comment by driskull** [comment]
I don't think this will be part of the scope of the GeoForm right now. I would look more towards the crowdsource polling app for this.

We can maybe review this at a later time
