### ISSUE TITLE
locationSearchOptions don't respect the name defined in the config when reordered

### ISSUE THREAD

**Issue by chris-fox** [Esri/geoform-template-js#511]
Currently the location search options are defined like below.
    
"locationSearchOptions": {
      "enableMyLocation": true,
      "enableSearch": true,
      "enableLatLng": true,
      "enableUSNG": false,
      "enableMGRS": false,
      "enableUTM": false
    },

If instead the config is defined as below, with the same boolean state but in a different order you get unexpected results in the form. It seems to be honoring the order of the properties not the name. In the example below what you see in the form is that MGRS and UTM are enabled but Search and LatLng are disabled.

"locationSearchOptions": {
      "enableMyLocation": true,
      "enableUSNG": false,
      "enableMGRS": false,
      "enableUTM": false
      "enableSearch": true,
      "enableLatLng": true,
    },

**Comment by driskull** [comment]
thanks @chris-fox !

**Comment by chris-fox** [comment]
@driskull, thanks looks good! Only noticed this while i was working on a python script to create new items items and the search options were written in a different order.
