### ISSUE TITLE
List of field attributes?

### ISSUE THREAD

**Issue by gismcieri** [Esri/geoform-template-js#512]
Hi,
Is there a list of field attributes available. The one i can't seem to find is required.
```
    "fields": {
	"BusinessLicenseTest_5614": [{
    "name": "OwnerName", // field ID
    "alias": "Owner Name", // label
    "fieldDescription": "", // help text
    "visible": true, // show this field?
    "typeField": false, // subtype field?
    "tooltip": "", // placeholder text
    "displayType": "text", // text, checkbox, radio, textarea, url, email
	"requiredFields": true 
  }
```

I have tried "required" = true,  "requiredField": true and "requiredFields": true  and none make the field required.  The only way i can get a field required is by if the field is a dropdown and set typeField = true.

Am i missing something?

Thanks,
Matt

**Comment by driskull** [comment]
Hey @gismcieri 

Try setting `nullable: false` on the field.

**Comment by gismcieri** [comment]
That worked thanks!
