### ISSUE TITLE
Coded Value Domain Description Not Shown in Viewer Mode

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#514]
This is from a student in my course. 

"When creating domains for this project I had two that I used "Coded Value Domain" for, the "Problem" and "Injured" domains. I had a few (~5) different options for these (Fire, Damaged Road, Power Line down or Minor Injury, Moderate Injury etc) so obviously there'd be 1-5 for codes for each. After uploading the feature layer to a web map and subsequently the GeoForm Web App, I noticed the Geo Form only displayed the actual code, not the description. So when a user went to view submissions they would see this: 
![image](https://cloud.githubusercontent.com/assets/4256979/17264823/da023572-563d-11e6-8b23-d8a2ba09a9c9.png)

From a purely operational standpoint this looks like it says "2 Injured" when in reality it means "Yes [there are injured], minor injuries" which could be quite misleading.

The thing is, the web map this app uses displays the information properly: 
![image](https://cloud.githubusercontent.com/assets/4256979/17264828/e1a34302-563d-11e6-99dc-debf05191e8c.png)

I don't completely know what is going on here but I thought I'd bring it to your attention. IT looks like it might be an issue with the App itself. Let me know if there are any solutions. "

**Comment by driskull** [comment]
We'll get this working better in 4x version
