### ISSUE TITLE
Is that possible to save the Form data to a PDF file

### ISSUE THREAD

**Issue by zhujingx** [Esri/geoform-template-js#518]
I'd like to see the way to save the form data to a PDF file, This way user could have a hard copy or digital copy of the data for what they submit. I am able to do a HTML format, like to know how to save a PDF format.

Thanks
Zhujing

**Comment by driskull** [comment]
Not currently. We will add a print page that will allow printing so this will be possible at a later time.

**Comment by driskull** [comment]
#501
