### ISSUE TITLE
Configure field in the defaults.js - changes do not apply to map

### ISSUE THREAD

**Issue by STGiese** [Esri/geoform-template-js#532]
How can I configure the fields shown in the geoform by customizing the default.js? I know that there is a fields-option where I can set an alias, the displayType an so on, but the changes do not apply to my map...
 The service-properties are shown below:
{
 "currentVersion": 10.31,
 "id": 1,
 "name": "Bürgerbeteiligung LPGT - Festsetzungen",
 "type": "Feature Layer",
 "description": "",
 "copyrightText": "",
 "defaultVisibility": true,

Any hints???
 Thanks in advance!! :-)

**Comment by driskull** [comment]
hey @STGiese the readme has infor for configuring the fields from the defaults.js

https://github.com/Esri/geoform-template-js/blob/master/README.md#configuring-fields

**Comment by STGiese** [comment]
I read these instructions, but they don't apply anyway... Here is my code (where "vorname" is the fieldname in the database):
"fields": {
       "1" : [{
           "name": "vorname",
           "alias": "Ihr Name",
           "visible": true,
           "displayType": "textarea"
       }]
}

**Comment by STGiese** [comment]
With the developertools enabled in Firefox I could manage to find out the correct ID... It was tricky, but it worked :-)
