### ISSUE TITLE
DotNet Proxy isn't working

### ISSUE THREAD

**Issue by randomblink** [Esri/geoform-template-js#538]
I've configured the GeoForm per ALL instructions. But the proxy isn't working.
The geoform is on an INTERNAL ONLY server. The AGOL Feature Layer and WebMap and Application are all shared with the Organization. I've got ClientID and ClientSecret setup in the proxy.

Nothing... it asks for sign on everytime.

**Comment by driskull** [comment]
hey @randomblink I think [this comment](https://github.com/Esri/geoform-template-js/issues/488#issuecomment-160829219) might be what you need.

```js
myTemplate.startup().then(function (config) {
                urlUtils.addProxyRule({
                urlPrefix: "prefixToServiceUrl",  // Does this look right? This is what worked when testing with AppBuilder
                proxyUrl: config.proxyurl
                });
```

https://developers.arcgis.com/javascript/3/jsapi/esri.urlutils-amd.html#addproxyrule

Basically, you need to tell esri.urlUtils to use your proxy for a specific URL.

Let me know if that works and that is it and I'll update the readme to cover this.

-Matt

**Comment by randomblink** [comment]
Here's my problem... I'm not sure what I need to use for the 'prefixToServiceUrl' entry...
Here is the rest service url : https://cityoftulsa.maps.arcgis.com/sharing/rest/content/items/1e312d06f3f44867b970bc281c8e6357

Here is the url to the AGOL Application:
http://cityoftulsa.maps.arcgis.com/home/item.html?id=1e312d06f3f44867b970bc281c8e6357

Since we host the Rest Service on our own ESRI Server should I point to the rest service directly? AND how should I configure the Proxy rule in the Proxy.config file?

**Comment by randomblink** [comment]
For an example:

I entered the following...

index.html

>         require(["config/templateConfig", "application/template", "application/main", "esri/urlUtils"], function (templateOptions, Template, Main, urlUtils) {

and

> 				urlUtils.addProxyRule({
>                 	urlPrefix: "https://cityoftulsa.maps.arcgis.com/sharing/rest/content/items/1e312d06f3f44867b970bc281c8e6357",  
>                 	proxyUrl: config.proxyurl
>                 });				
> 

Then I added to the proxy config like so...

proxy.config

> 		<serverUrl  url="https://cityoftulsa.maps.arcgis.com/sharing/rest/content/items/1e312d06f3f44867b970bc281c8e6357" 
> 					clientId="ClientIDGoesHere" clientSecret="ClientSecretGoesHere" 
>                     oauth2Endpoint="https://cityoftulsa.maps.arcgis.com/sharing/oauth2/" matchAll="true"/>
> 

But it does not work...

**Comment by driskull** [comment]
hey @randomblink,

The URL prefix should be the URL to the rest service, not the portal item like I see above. It should only be a partial URL up to the service so that it can perform queries on the service and be able to identify that it should use the proxy.

For example the following prefix would proxy anything after `/`

`https://services1.arcgis.com/XLY7M6F9oPzjvKmJ/ArcGIS/rest/services/Bruxelles_metro_lines/`

So this would work:

`https://services1.arcgis.com/XLY7M6F9oPzjvKmJ/ArcGIS/rest/services/Bruxelles_metro_lines/FeatureServer/0/query?f=json&outFields=Type%2COBJECTID&outSR=102100&returnGeometry=false&spatialRel=esriSpatialRelIntersects&where=(UPPER(Type)%20LIKE%20%27%25RED%25%27)`

Everything else you have looks good.

**Comment by randomblink** [comment]
The current rest service that this is feeding from is located on our ArcServer.
http://maps.cityoftulsa.org/gis/rest/services/LGDM/Address/FeatureServer/0

When I use that URL the geoform still doesn't work.

![image](https://user-images.githubusercontent.com/235770/31398619-2e25670e-adaf-11e7-9304-4dc4ad623b3b.png)

When I hover of the App ID in the login form I get the following URL.
https://cityoftulsa.maps.arcgis.com/sharing/rest/content/items/1e312d06f3f44867b970bc281c8e6357

But using that URL the geoform still doesn't work.

**Comment by driskull** [comment]
Can you see if the network tab is using the proxy when calling for the service? That's a good first step. If not, make sure you have the proxyUrl set int he config.js as well.

If that doesn't work, try adding proxy rules for the rest URL without the http/https. like so:

```js
urlUtils.addProxyRule({
  urlPrefix: "route.arcgis.com",
  proxyUrl: "<url_to_proxy>"
});
```

**Comment by randomblink** [comment]
Ok... So in Index.html I have the following...
![image](https://user-images.githubusercontent.com/235770/31399077-a9836d5a-adb0-11e7-8f90-197574b1c84a.png)

In the proxy.config I have the following...
![image](https://user-images.githubusercontent.com/235770/31399112-c673fbaa-adb0-11e7-8318-3557c13068d7.png)

Is this what you meant by the service URL?
And it doesn't matter if I leave the **https://** or not. It still asks for login.

**Comment by driskull** [comment]
Yeah I don't think that will work. I think you need the actual URL to the rest service, not to the portal item.

For example: 
```js
{
            "serverUrl" : [
                {
                    "url": "http://route.arcgis.com",
                    "oauth2Endpoint": "https://www.arcgis.com/sharing/oauth2",
                    "clientId": "6Xo1d-example-9Kn2",
                    "clientSecret": "5a5d50-example-c867b6efcf969bdcc6a2",
                    "rateLimit": "120",
                    "rateLimitPeriod": "60",
                    "matchAll": true
                }
            ]
        },
```

So in the index addProxyRule, you need a partial match to the service URL, not the portal item and in the proxy.config you need the same for the url.

**Comment by driskull** [comment]
You should be able to go to the item in your portal and view the service URL to the rest service.

**Comment by randomblink** [comment]
Even if the service URL is on an ArcServer and not AGOL?

**Comment by randomblink** [comment]
http://maps.cityoftulsa.org/gis/rest/services/LGDM/Address/FeatureServer/0

**Comment by driskull** [comment]
yeah, like that... so the partial would be: `maps.cityoftulsa.org/gis/rest/services/LGDM/Address/FeatureServer/0`

**Comment by driskull** [comment]
We'll get this working :)

If I cant get it working ill find someone who will

**Comment by randomblink** [comment]
Did the partial in index.html, no go.
Used the partial in the proxy.config, no go.
Thank you so much. I tried to open a support ticket with ESRI yesterday and they still haven't called me back... this is a lifesaver.

**Comment by driskull** [comment]
I think the best thing to do now would be to start debugging it. Open up the console and network tab and see what URL is prompting the identity manager to request credentials. Maybe post a screenshot of the network tab and we can see if its even going through the proxy or if it is going through it but the credentials aren't working.

**Comment by randomblink** [comment]
Here is the CONSOLE tab...
https://youtu.be/O8rUfCFSXtM

Here is the NETWORK tab...
https://youtu.be/soDZSF5LGL4

I'm not seeing anything...

**Comment by randomblink** [comment]
It doesn't look like the proxy is even looked at. Which is frustrating. But seems apropos.

**Comment by driskull** [comment]
Yes, it looks like its the org item that is prompting the proxy.

So we need another entry for that in the proxy config.


```
{
            "serverUrl" : [
                {
                    "url": "maps.cityoftulsa.org/gis",
                    "oauth2Endpoint": "https://cityoftulsa.maps.arcgis.com/sharing/oauth2",
                    "clientId": "INSERT",
                    "clientSecret": "INSERT",
                    "matchAll": true
                }
            ]
        },
```

And add another proxy rule:

urlUtils.addProxyRule({
  urlPrefix: "maps.cityoftulsa.org/gis",
  proxyUrl: "<url_to_proxy>"
});

**Comment by randomblink** [comment]
Added those both and got the same...
https://youtu.be/kf2_1oLH4oI

**Comment by randomblink** [comment]
Index.html setup
![image](https://user-images.githubusercontent.com/235770/31402538-e31efe34-adbb-11e7-8626-d84e3d2eaadb.png)

**Comment by randomblink** [comment]
proxy.config setup
![image](https://user-images.githubusercontent.com/235770/31402576-021b64bc-adbc-11e7-8efd-d1e6f61491fd.png)

**Comment by driskull** [comment]
In the network tab, click on the `?self=` links and see what URL is prompting the username/password. note if its calling self with HTTP vs HTTPS. If its using https, you'll need to use https in the proxy.config as well.

![screen shot 2017-10-10 at 11 08 55 am](https://user-images.githubusercontent.com/1231455/31402667-8dc30724-adab-11e7-923d-ed654d0e471e.png)

Also make sure that in your app in the `config.js` the `proxyurl` is entered to point to your proxy on your server. Can you send a screen of that?

**Comment by randomblink** [comment]
default.js setup
![image](https://user-images.githubusercontent.com/235770/31403148-e6126a2a-adbd-11e7-9011-9b3bb7708515.png)

First self?f=...
![image](https://user-images.githubusercontent.com/235770/31403202-1136c99e-adbe-11e7-839d-ba9449b7e96d.png)

Second / Last self?f=...
![image](https://user-images.githubusercontent.com/235770/31403225-237e784a-adbe-11e7-95c5-e080cb94f037.png)

**Comment by randomblink** [comment]
I tried adding in those urls...
https://cityoftulsa.maps.arcgis.com/sharing/rest
https://www.arcgis.com/sharing/rest
https://maps.cityoftulsa.org/gis
https://maps.cityoftulsa.org/gis/rest/services/LGDM/Address/FeatureServer/0

Both to index.html and proxy.config with no luck.

**Comment by driskull** [comment]
Can you share the network request for the item beginning with "1e..." Is that trying to go through the proxy at all?

**Comment by randomblink** [comment]
![image](https://user-images.githubusercontent.com/235770/31403661-6042efda-adbf-11e7-884e-09dce2fe10ee.png)

**Comment by randomblink** [comment]
Does not appear to be trying to go through the proxy.

**Comment by randomblink** [comment]
Wait... the RESPONSE for this entry shows the following.

{"error":{"code":403,"messageCode":"GWM_0003","message":"You do not have permissions to access this resource or perform this operation.","details":[]}}

**Comment by driskull** [comment]
yes, but its not prompting the proxy. So add another proxyrule for `cityoftulsa.maps.arcgis.com/sharing/rest/content/items/<ITEMID>`

**Comment by driskull** [comment]
Also make sure the proxy.config has an entry for `https://cityoftulsa.maps.arcgis.com`

**Comment by randomblink** [comment]
index.html
![image](https://user-images.githubusercontent.com/235770/31403911-36583fe4-adc0-11e7-8d3e-228380d59765.png)

proxy.config
![image](https://user-images.githubusercontent.com/235770/31403946-50c3fd32-adc0-11e7-871f-0cf0ae99968f.png)

**Comment by randomblink** [comment]
Still not working

**Comment by driskull** [comment]
Make sure to add the proxyRule before the `myTemplate.startup()` here:

https://user-images.githubusercontent.com/235770/31399077-a9836d5a-adb0-11e7-8f90-197574b1c84a.png

**Comment by driskull** [comment]
I'm thinking the item is being requested before the proxyRule is in effect

**Comment by randomblink** [comment]
Ok...
https://youtu.be/qoWKnhxkYtA

We might be getting closer.

**Comment by driskull** [comment]
Yes! some progress. It is going to the proxy now but credentials arent working. So now we just need to get the proxy.config to pass the correct credentials to the correct urls.

The clientId and clientSecret are valid right? And the Urls are matching? Make sure that urls have both http and https if a request is going via http.

**Comment by driskull** [comment]
Looks like the item one isn't returning anything. it should return data for the item.

**Comment by randomblink** [comment]
I'll be back to this later. I have to eat. It's almost 2:30pm here. Sorry.

**Comment by randomblink** [comment]
Ok... I have returned.

**Comment by driskull** [comment]
Just need to figure out which URL is not returning the data needed and then add it to the proxy config to pass authentication through.

**Comment by randomblink** [comment]
I think it's this one:
https://cityoftulsa.maps.arcgis.com/sharing/rest/content/items/1e312d06f3f44867b970bc281c8e6357

But at this point I'm so lost...

**Comment by driskull** [comment]
What is the `"sharinghost": "https://www.arcgis.com",` in the config? it should be `"sharinghost": "https://cityoftulsa.maps.arcgis.com",`

**Comment by randomblink** [comment]
![image](https://user-images.githubusercontent.com/235770/31410535-81637f4e-add4-11e7-9e1b-842ca9c7b0bc.png)

**Comment by driskull** [comment]
looks good...

> I have the appid but not the mapid...
> Should I adjust that?

No that should be fine.

I'm lost too :(

**Comment by randomblink** [comment]
I'm adding the mapid.

**Comment by randomblink** [comment]
![image](https://user-images.githubusercontent.com/235770/31411311-d68ed8cc-add6-11e7-9788-bb930df96fc8.png)

![image](https://user-images.githubusercontent.com/235770/31411341-eae95e46-add6-11e7-8ba8-66ef2149da94.png)

403... GWM_0003

**Comment by driskull** [comment]
or you use `username` and `password` in there.

**Comment by randomblink** [comment]
No I had tried a few combinations... It should be clientId and clientSecret
I fixed it... Now I am getting this...
![image](https://user-images.githubusercontent.com/235770/31411598-b40592a4-add7-11e7-86fe-544498c0def3.png)

**Comment by randomblink** [comment]
IT WORKS!!!!

**Comment by driskull** [comment]
![200w_d](https://user-images.githubusercontent.com/1231455/31411691-389e8f90-adc7-11e7-97ad-61f0b2b377d5.gif)

**Comment by randomblink** [comment]
index.html
![image](https://user-images.githubusercontent.com/235770/31411655-e2f6c632-add7-11e7-88d7-dad6bc5b94ac.png)

proxy.config
![image](https://user-images.githubusercontent.com/235770/31411688-f9f6e240-add7-11e7-96d8-c95851b30314.png)

On a whim I copied the proxy rules for the APP ID and swapped out the WEBMAP ID and it works...

**Comment by driskull** [comment]
cool! you might just be able to use up to the `content/items` to eliminate both entries.

**Comment by driskull** [comment]
#540

**Comment by randomblink** [comment]
That is correct. I used the following...

proxy.config
<serverUrl  url="https://cityoftulsa.maps.arcgis.com/sharing/rest/content/items/" clientId="INSERT" clientSecret="INSERT" oauth2Endpoint="https://cityoftulsa.maps.arcgis.com/sharing/oauth2/" matchAll="true"/>

index.html
urlUtils.addProxyRule({ urlPrefix: "cityoftulsa.maps.arcgis.com/sharing/rest/content/items/", proxyUrl: "http://cotgis/DotNet/proxy.ashx" });

But I included both the WEBMAP ID and the APP ID in the default.js.

**Comment by pdenny** [comment]
This issue thread has been hugely helpful for me, but I have not quite gotten it working. I've created a new issue [here](https://github.com/Esri/geoform-template-js/issues/549)
