### ISSUE TITLE
Configuration wizard bugs

### ISSUE THREAD

**Issue by Jking-GIS** [Esri/geoform-template-js#555]
1. When you enter the configuration wizard and navigate to page "2: Webmap", if you choose a webmap with no editable layers, the rest of the configuration wizard has no layer to use for reference. For example, on page "5: Fields", the layer selection dropdown will have no values and you will be able to choose no fields. This can be fixed by adding in a condition to check the validity of layerIndex on line 1056 of builder.js.

2. If you pick a valid webmap from page "2: Webmap" and navigate through the page "3: Layer" without changing it from the default option of "All Layers", then page "5: Fields" will still be using field information from the default webmap in the configuration wizard. This can be fixed around line 1180 of builder.js by using the LAST key in this.fieldInfo, instead of using the counter to check for the FIRST key in this.fieldInfo.

**Comment by kellyhutchins** [comment]
Thanks! We'll get this fixed in the builder.

**Comment by driskull** [comment]
I believe this should be fixed now.
