### ISSUE TITLE
Uncaught TypeError: Cannot read property '3' of null

### ISSUE THREAD

**Issue by wspiking** [Esri/geoform-template-js#556]
Hello,

I'm trying to deploy a geoform on our webserver and keep getting the error below in dev tools.  I get the same error when launching your geoform from http://esri.github.io/geoform-template-js/.  Any ideas?  I've made both my webmap, app, and feature layers public in testing.  Not sure what else to try.  Any help would be greatly appreciated.

Thank you,

Bill

![screenshot](https://user-images.githubusercontent.com/5851986/53965213-5ec97f80-40b6-11e9-8993-ad46fc9d4101.PNG)

**Comment by ccrozek** [comment]
I'm having the same issue. Plugged the appid into the default.js, changed the sharing host, made everything public, and just gets stuck on the loading gif.

**Comment by wspiking** [comment]
Thank you for verifying @ccrozek .  Any ideas on what could be causing the issue @driskull?

**Comment by driskull** [comment]
I'll check it out 👀

**Comment by wspiking** [comment]
Thanks!

**Comment by driskull** [comment]
Fixed!

**Comment by ccrozek** [comment]
can confirm that it works for me now with my geoform. Thanks so much!!
